version: '2'
services:

  # http://localhost:8000
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    volumes:
      - '../symfony_app:/app'
    environment:
      - SYMFONY_PROJECT_NAME=myapp
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - MARIADB_USER=bobby
      - MARIADB_PASSWORD=tables
      - MARIADB_DATABASE=symfony_app
      - SYMFONY_DATABASE_PASSWORD=tables
    depends_on:
      - mariadb
    networks:
      - project_symfony_network

  mariadb:
    image: 'bitnami/mariadb:10.3'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bobby
      - MARIADB_PASSWORD=tables
      - MARIADB_DATABASE=symfony_app
    networks:
      - project_symfony_network

  # http://localhost:8080
  phpmyadmin:
    environment:
      - MYSQL_ROOT_PASSWORD=
      - PMA_HOST=mariadb
      # if you don't want to log in every time to phpmyadmin
      # leave the following variables intact
      - PMA_USER=bobby
      - PMA_PASSWORD=tables
      - PMA_ARBITRARY=1
    image: phpmyadmin/phpmyadmin
    ports:
      - '8080:80'
    networks:
      - project_symfony_network

volumes:
  data:

networks:
  project_symfony_network:
